TITLE: "🏙️ Прогноз стоимости недвижимости"
DESCRIPTION: "Введите данные о недвижимости, чтобы получить оценку стоимости за квадратный метр"
LOCATION_SECTION: "Местоположение объекта"
DETAILS_SECTION: "Детали объекта"
TRANSPORT_SECTION: "Транспорт и доступность"
COORDINATES_SECTION: "Географические координаты"
MODEL_SELECTION_SECTION: "Выбор модели для предсказания"
PREDICTION_RESULT_LABEL: "💲 Оценка цены за квадратный метр"
PREDICT_BUTTON_LABEL: "📊 Оценить"
LOADING_MESSAGE: "#### ⏳ Пожалуйста, подождите, пока идет расчет оценки..."